### PR TITLE
add download feature

### PR DESCRIPTION
**Pull request by JulianMar**
it can be disabled via the buttons config object.

I had some problems with the compilation of the dist files, maybe you can help me there?

### CODE REVIEW

**Comment by JulianMar** [comment]
Hi @Krato, I saw you are a frequent contributor. Can you maybe take a look at this PR? Thank you!

**Comment by Krato** [comment]
I will check soon 👍🏽

**Comment by JulianMar** [comment]
@Krato sorry to ask again, but this feature would be really nice to have

**Comment by LucasLeandro1204** [comment]
@JulianMar it's possible to have multiSelect and folder download?

**Comment by Krato** [comment]
Merged in master but with some ui changes and download feature in field also.

Thanks for your PR :D

**Pull request merged**
